import { useEffect, useState } from 'react'
import type { ApiCall, Integration, IntegrationInput, Provider } from './types'
import { Alert, Icon, Loading, Modal } from './ui'
export function Integrations({ call }: { call: ApiCall }) {
  const [items, setItems] = useState<Integration[] | null>(null), [error, setError] = useState(''), [success, setSuccess] = useState('')
  const [editing, setEditing] = useState<Integration | null>(null), [retry, setRetry] = useState(0)
  useEffect(() => { const controller = new AbortController(); Promise.all((['MELHOR_ENVIO', 'CORREIOS'] as Provider[]).map(provider => call<Integration>(`/admin/shipping/providers/${provider}`, { signal: controller.signal }))).then(setItems).catch(e => { if (e.name !== 'AbortError') setError(e.message) }); return () => controller.abort() }, [call, retry])
  return <><div className="page-heading"><div><p className="eyebrow">SUAS CONTAS, SUAS CONDIÇÕES</p><h1>Contas de frete.</h1><p>Use um intermediador ou aproveite seu contrato direto com os Correios.</p></div></div><Alert>{error}</Alert><Alert success>{success}</Alert>
    {!items && !error && <Loading/>}{error && !items && <button className="secondary" onClick={() => { setError(''); setRetry(n => n + 1) }}>Tentar novamente</button>}
    {items && <div className="integration-grid">{items.map(item => <section className="panel integration-card" key={item.provider}><div className="integration-top"><span className={`provider-mark ${item.provider === 'CORREIOS' ? 'postal' : ''}`}>{item.provider === 'CORREIOS' ? 'C' : 'me'}</span><span className={`badge ${item.enabled && item.credentialsConfigured ? 'green' : ''}`}>{item.enabled && item.credentialsConfigured ? 'Habilitada' : item.credentialsConfigured ? 'Desativada' : 'Não configurada'}</span></div><h2>{item.provider === 'CORREIOS' ? 'Correios com contrato' : 'Melhor Envio'}</h2><p>{item.provider === 'CORREIOS' ? 'Configure sua conta CWS, contrato e cartão de postagem.' : 'Cadastre o token de cotação da conta do lojista.'}</p><dl><div><dt>CEP de origem</dt><dd>{item.originPostalCode || 'Não informado'}</dd></div><div><dt>Ambiente</dt><dd>{item.sandbox ? 'Testes' : 'Produção'}</dd></div><div><dt>Credenciais</dt><dd>{item.credentialsConfigured ? 'Cadastradas com segurança' : 'Aguardando configuração'}</dd></div></dl><button className="secondary full" onClick={() => setEditing(item)}>{item.credentialsConfigured ? 'Editar configuração' : 'Configurar conta'}<Icon name="arrow" size={17}/></button></section>)}</div>}
    <div className="help-strip"><Icon name="shield"/><p><strong>Suas credenciais ficam protegidas.</strong> Elas não são exibidas após salvar. Uma configuração salva ainda precisa ser validada com uma cotação no checkout.</p></div>
    <section className="panel guide"><h2>Como deixar tudo pronto</h2><ol><li><span>01</span><div><strong>Configure sua conta</strong><p>Informe origem e credenciais do ambiente que pretende usar.</p></div></li><li><span>02</span><div><strong>Cadastre as embalagens</strong><p>Peso e dimensões devem incluir a embalagem de cada unidade.</p></div></li><li><span>03</span><div><strong>Escolha os serviços</strong><p>Adicione as formas de entrega e confira uma cotação antes de ativá-las.</p></div></li></ol><p className="field-help">O ambiente de testes não pode ser usado para vendas reais. Etiquetas e postagem são realizadas no painel do provedor nesta versão.</p></section>
    {editing && <IntegrationEditor key={editing.provider} integration={editing} call={call} close={() => setEditing(null)} saved={item => { setItems(current => current?.map(existing => existing.provider === item.provider ? item : existing) || []); setEditing(null); setSuccess('Configuração salva. Confira uma cotação no checkout para validar a conta.'); setError('') }}/>}</>
}
function IntegrationEditor({ integration, call, close, saved }: { integration: Integration; call: ApiCall; close: () => void; saved: (integration: Integration) => void }) {
  const [sandbox, setSandbox] = useState(integration.sandbox), [enabled, setEnabled] = useState(integration.enabled)
  const [replace, setReplace] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState('')
  const correios = integration.provider === 'CORREIOS'
  const changedEnvironment = sandbox !== integration.sandbox
  const showCredentials = !integration.credentialsConfigured || replace || changedEnvironment
  const credentialsRequired = replace || changedEnvironment || (enabled && !integration.credentialsConfigured)
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget); const text = (name: string) => String(form.get(name) || '').trim()
    const body: IntegrationInput = { originPostalCode: text('originPostalCode'), sandbox, enabled }
    if (correios) {
      body.contractCode = text('contractCode'); body.postingCard = text('postingCard'); body.contractRegional = Number(form.get('contractRegional'))
      if (text('username') || text('accessCode')) { if (!text('username') || !text('accessCode')) { setError('Informe o usuário e o código de acesso juntos.'); return }; body.username = text('username'); body.accessCode = text('accessCode') }
    } else if (text('accessToken')) body.accessToken = text('accessToken')
    setBusy(true); setError('')
    try { const result = await call<Integration>(`/admin/shipping/providers/${integration.provider}`, { method: 'PUT', body }); saved(result) }
    catch (e) { setError((e as Error).message); setBusy(false) }
  }
  return <Modal title={correios ? 'Configurar Correios' : 'Configurar Melhor Envio'} subtitle="As configurações são exclusivas desta loja." close={close} busy={busy}><form onSubmit={submit} autoComplete="off"><fieldset disabled={busy}><Alert>{error}</Alert><div className="form-grid"><label>CEP de origem<input name="originPostalCode" required pattern="[0-9]{8}" inputMode="numeric" maxLength={8} placeholder="01001000" defaultValue={integration.originPostalCode || ''}/></label><label>Ambiente<select aria-label="Ambiente" value={sandbox ? 'test' : 'production'} onChange={event => setSandbox(event.target.value === 'test')}><option value="test">Testes</option><option value="production">Produção</option></select></label></div>
    {changedEnvironment && <div className="info-box">Ao mudar de ambiente, informe as credenciais correspondentes. Contas de testes e produção são separadas.</div>}
    {correios && <><div className="form-grid"><label>Número do contrato<input name="contractCode" required inputMode="numeric" pattern="[0-9]{1,30}" maxLength={30} defaultValue={integration.contractCode || ''}/></label><label>Cartão de postagem<input name="postingCard" required inputMode="numeric" pattern="[0-9]{1,30}" maxLength={30} defaultValue={integration.postingCard || ''}/></label></div><label>Regional do contrato (DR)<input type="number" name="contractRegional" min="0" max="99" step="1" required defaultValue={integration.contractRegional ?? ''}/><small>Consulte a Superintendência Estadual nos documentos do contrato.</small></label></>}
    {integration.credentialsConfigured && !changedEnvironment && <label className="check-label"><input type="checkbox" checked={replace} onChange={event => setReplace(event.target.checked)}/>Substituir as credenciais cadastradas</label>}
    {showCredentials ? correios ? <><label>Usuário Meu Correios<input name="username" maxLength={120} required={credentialsRequired} autoComplete="off"/></label><label>Código de acesso à API CWS<input type="password" name="accessCode" maxLength={500} required={credentialsRequired} autoComplete="new-password"/><small>Use o código de API, não a senha de acesso à Planno.</small></label></> : <label>Token de acesso do Melhor Envio<input type="password" name="accessToken" maxLength={2000} required={credentialsRequired} autoComplete="new-password"/><small>O token precisa permitir cotação. Se expirar, substitua-o aqui.</small></label> : <p className="field-help"><Icon name="shield" size={15}/> As credenciais atuais serão preservadas.</p>}
    <label className="check-label"><input type="checkbox" checked={enabled} onChange={event => setEnabled(event.target.checked)}/>Habilitar esta conta para cotação</label><p className="field-help">Salvar não cria formas de entrega. Depois, adicione os serviços desejados na aba Entregas.</p><div className="form-actions"><button type="button" className="secondary" onClick={close}>Cancelar</button><button className="primary" type="submit">{busy ? 'Salvando…' : 'Salvar configuração'}</button></div></fieldset></form></Modal>
}
