import { useEffect, useState } from 'react'
import type { ApiCall, Product, ShippingPackage } from './types'
import { Alert, Icon, Loading, Modal } from './ui'
export function Products({ call }: { call: ApiCall }) {
  const [page, setPage] = useState(0)
  return <><div className="page-heading"><div><p className="eyebrow">MEDIDAS QUE FAZEM DIFERENÇA</p><h1>Embalagens dos produtos.</h1><p>Cadastre peso e dimensões para calcular o frete sem surpresas.</p></div></div><div className="info-box">Meça cada unidade <strong>já embalada</strong>. No contrato direto com Correios, cada unidade será enviada como um pacote separado.</div><ProductPage key={page} call={call} page={page} changePage={setPage}/></>
}
function ProductPage({ call, page, changePage }: { call: ApiCall; page: number; changePage: (page: number) => void }) {
  const [products, setProducts] = useState<Product[] | null>(null), [error, setError] = useState(''), [success, setSuccess] = useState('')
  const [editing, setEditing] = useState<Product | null>(null), [retry, setRetry] = useState(0)
  useEffect(() => { const controller = new AbortController(); call<Product[]>(`/admin/products?page=${page}&size=20`, { signal: controller.signal }).then(setProducts).catch(e => { if (e.name !== 'AbortError') setError(e.message) }); return () => controller.abort() }, [call, page, retry])
  return <><Alert>{error}</Alert><Alert success>{success}</Alert>{!products && !error && <Loading/>}{error && !products && <button className="secondary" onClick={() => { setError(''); setRetry(n => n + 1) }}>Tentar novamente</button>}
    {products && <section className="panel"><div className="panel-heading"><div><h2>Produtos da loja</h2><p>Embalagens incompletas impedem a cotação automática.</p></div><span className="count">Página {page + 1}</span></div>{products.length === 0 ? <div className="empty"><Icon name="box" size={36}/><h3>{page ? 'Você chegou ao fim da lista' : 'Seus produtos aparecerão aqui'}</h3><p>{page ? 'Volte para a página anterior.' : 'Após cadastrar produtos na loja, configure as embalagens nesta tela.'}</p></div> : <div className="product-list">{products.map(product => <article className="product-row" key={product.id}><span className="row-icon"><Icon name="box"/></span><div className="method-info"><h3>{product.name}</h3><p>SKU {product.sku} · {product.status === 'ACTIVE' ? 'Ativo' : 'Inativo'}</p></div><div className="package-details">{product.shippingPackage ? <><strong>{product.shippingPackage.weightKg} kg</strong><span>{product.shippingPackage.widthCm} × {product.shippingPackage.heightCm} × {product.shippingPackage.lengthCm} cm</span></> : <span className="badge amber">Embalagem pendente</span>}</div><button className="secondary compact" onClick={() => setEditing(product)} aria-label={`Configurar embalagem de ${product.name}`}><Icon name="edit" size={15}/>Configurar</button></article>)}</div>}<div className="pagination"><span>Até 20 produtos por página</span><div><button className="secondary compact" disabled={page === 0} onClick={() => changePage(page - 1)}>Anterior</button><button className="secondary compact" disabled={products.length < 20} onClick={() => changePage(page + 1)}>Próxima</button></div></div></section>}
    {editing && <PackageEditor product={editing} call={call} close={() => setEditing(null)} saved={pack => { setProducts(current => current?.map(product => product.id === editing.id ? { ...product, shippingPackage: pack } : product) || []); setEditing(null); setSuccess('Embalagem atualizada. As próximas cotações usarão essas medidas.'); setError('') }}/>}</>
}
function PackageEditor({ product, call, close, saved }: { product: Product; call: ApiCall; close: () => void; saved: (pack: ShippingPackage) => void }) {
  const [busy, setBusy] = useState(false), [error, setError] = useState('')
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget); const body = Object.fromEntries(['weightKg', 'widthCm', 'heightCm', 'lengthCm'].map(name => [name, Number(form.get(name))]))
    setBusy(true); setError('')
    try { saved(await call<ShippingPackage>(`/admin/products/${product.id}/shipping-package`, { method: 'PUT', body })) } catch (e) { setError((e as Error).message); setBusy(false) }
  }
  return <Modal title="Embalagem do produto" subtitle={product.name} close={close} busy={busy}><form onSubmit={submit}><fieldset disabled={busy}><Alert>{error}</Alert><div className="package-illustration"><Icon name="box" size={72}/><p>Produto + embalagem<br/><strong>Uma unidade pronta para envio</strong></p></div><div className="form-grid">{([['weightKg', 'Peso (kg)'], ['widthCm', 'Largura (cm)'], ['heightCm', 'Altura (cm)'], ['lengthCm', 'Comprimento (cm)']] as const).map(([name, label]) => <label key={name}>{label}<input type="number" name={name} required min={name === 'weightKg' ? '0.001' : '0.1'} max="1000" step={name === 'weightKg' ? '0.001' : '0.1'} defaultValue={product.shippingPackage?.[name] ?? ''}/></label>)}</div><p className="field-help">Exemplo: 500 gramas = 0,5 kg. Medidas incorretas podem gerar cobrança adicional da transportadora.</p><div className="form-actions"><button className="secondary" type="button" onClick={close}>Cancelar</button><button className="primary" type="submit">{busy ? 'Salvando…' : 'Salvar embalagem'}</button></div></fieldset></form></Modal>
}
